name:  Publish Python Package

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.2"
      - name: Install Python 3.14
        run: uv python install 3.14
      - name: Build package
        run: uv builds
      - name: Publish package
        run: uv publish